name: test_app
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

dependencies:
  args: ^2.4.0
  orm: ^4.0.1
  postgres: ^3.1.1
  shelf: ^1.4.0
  shelf_hotreload: ^1.5.0
  shelf_router: ^1.1.0

dev_dependencies:
  http: ^1.1.0
  lints: ^2.1.0
  test: ^1.24.0
